run:
	irun ../00_TESTBED/tb_3to8dec.v  -debug  -notimingchecks -loadpli1 debpli:novas_pli_boot
run1:	
	irun ../00_TESTBED/tb_6to64dec.v -debug  -notimingchecks -loadpli1 debpli:novas_pli_boot
clean:
	rm -rf INCA_libs nWaveLog
	rm -rf *.fsdb
	rm -rf *.log
	rm -rf *~
	rm -rf ./Netlist/*.*
	rm -rf ./Report/*.*
	rm -rf dwsvf*
	rm -rf alib*
	rm -rf default.svf
	rm -rf alib-52
	rm -rf *-verilog.*
	rm -rf *.mr
	rm -rf diff_syn
	rm -rf novas*
	rm -rf irun*

         
